---
title: "Udacity EAD Lesson 3"
author: "Alex Zuo"
date: "April 16, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
getwd()
list.files()
pf<-read.csv("pseudo_facebook.tsv", sep="\t")
names(pf)
```


##histogram of users' birthdays
```{r}
library(ggplot2)
library(ggthemes)

names(pf)

qplot(x=dob_day, data=pf) + 
  scale_x_continuous(breaks=1:31)


ggplot(aes(x = dob_day), data = pf) + 
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = 1:31)

qplot(x=dob_day, data=pf) + 
  scale_x_continuous(breaks=1:31) +
  facet_wrap(~dob_month, ncol=3)

ggplot(data = pf, aes(x = dob_day)) + 
  geom_histogram(binwidth = 1) + 
  scale_x_continuous(breaks = 1:31) + 
  facet_wrap(~dob_month)

```


## friend count
```{r}
names(pf)
qplot(x=friend_count, data=pf, xlim=c(0, 1000))

qplot(x=friend_count, data=pf)+
  scale_x_continuous(limits = c(0, 1000))

qplot(x=friend_count, data=pf, binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))+
  facet_wrap(~gender, ncol=2)

qplot(x=friend_count, data=subset(pf, !is.na(gender)), binwidth = 25) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50))+
  facet_wrap(~gender)
  
```


## statistics by gender
```{r}
table(pf$gender)
by(pf$friend_count, pf$gender, summary)
?by

```


## tenure
```{r}

qplot(x=tenure/365, data=pf, binwidth=.25,
      xlab = "Number of years using facebook",
      ylab = "Number of uers in sample",
      color=I("black"), fill=I("#099DD9"))+
  scale_x_continuous(breaks = seq(1, 7,1), limits = c(0,7))

```


## age
```{r}
qplot(x=age, data=pf, binwidth=1,
      xlab = "ages of facebook users",
      ylab = "Number of uers in sample",
      color=I("black"), fill=I("#099DD9"))+
  scale_x_continuous(breaks = seq(0, 100,5), limits = c(10,100))

```

##transforming data
```{r}
library("gridExtra")
p1<-qplot(x=friend_count, data=pf)
p2<-qplot(x=log10(friend_count+1), data=pf)
p3<-qplot(x=sqrt(friend_count), data=pf)

grid.arrange(p1, p2, p3, ncol=1)


logScale<-qplot(x=log10(friend_count+1), data=pf)
countScale<-ggplot(aes(x=friend_count), data=pf)+
  geom_histogram()+
  scale_x_log10()

grid.arrange(p1, logScale, countScale, ncol=3)

qplot(x=friend_count, data=pf)+
  scale_x_log10()

```

## frequency polygons
```{r}
qplot(x=friend_count, data=subset(pf, !is.na(gender)), binwidth = 10) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) +
  facet_wrap(~gender)

qplot(x=friend_count, y=..count../sum(..count..),
      data=subset(pf, !is.na(gender)),
      xlab="friend count",
      ylab="proportion of users with that friend count",
      binwidth = 10, geom = "freqpoly", color=gender) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) 

names(pf)
table(pf$likes)
qplot(x=likes, data=pf, geom = "freqpoly", color=gender)


qplot(x=likes, y=..count../sum(..count..),
      data=subset(pf, !is.na(gender)),
      xlab="like count",
      ylab="proportion of users with that like count",
      binwidth = 10, geom = "freqpoly", color=gender) +
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) 


qplot(x=www_likes, data=pf, geom = "freqpoly", color=gender) + 
  scale_x_continuous()+
  scale_x_log10()

by(pf$www_likes, pf$gender, sum)

```

##boxplot
```{r}
qplot(x= gender, y = friend_count, data=subset(pf, !is.na(gender)), geom="boxplot") +
  scale_y_continuous(limits = c(0, 250)) 

qplot(x= gender, y = friend_count, 
      data=subset(pf, !is.na(gender)), geom="boxplot", ylim = c(0, 1000))

qplot(x= gender, y = friend_count, data=subset(pf, !is.na(gender)), geom="boxplot") +
  coord_cartesian(ylim = c(0, 1000)) 

qplot(x= gender, y = friend_count, data=subset(pf, !is.na(gender)), geom="boxplot") +
  coord_cartesian(ylim = c(0, 250))

by(pf$friend_count, pf$gender, summary)

```

## friendship initiated
```{r}

by(pf$friendships_initiated, pf$gender, summary)

```


## getting logical
```{r}
summary(pf$mobile_likes)
summary(pf$mobile_likes>0)
moible_check_in <- NA
pf$mobile_check_in <- ifelse(pf$mobile_likes>0, 1, 0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
str(pf)
summary(pf$mobile_check_in)

sum(pf$mobile_check_in == 1)/length(pf$mobile_check_in)

```






